# Generated by Django 2.0 on 2019-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='joining_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
