# Generated by Django 2.0 on 2019-08-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20190816_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
