# Generated by Django 2.0 on 2019-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20190816_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
